### ISSUE TITLE
Multiline options doesn't work and I misunderstand its usage

### ISSUE THREAD

**Issue by AlexVPopov** [rocketjob/rails_semantic_logger#101]
### Environment

Provide at least:
* Ruby Version: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
* Rails Version: Rails 6.0.3.1
* Semantic Logger Version / Rails Semantic Logger Version:
```
GIT
  remote: https://github.com/rocketjob/rails_semantic_logger.git
  revision: b24149ec2e6873fd74e6c8d7dbc53cbcfa64a82d
  ref: b24149ec2e6873fd74e6c8d7dbc53cbcfa64a82d
  specs:
    rails_semantic_logger (4.4.3)
      rack
      railties (>= 3.2)
      semantic_logger (~> 4.4)
```
* Other Application/framework names and versions (e.g. Puma, etc.).
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger:
```
=> #<RailsSemanticLogger::Options:0x00007fa59e69f460
 @add_file_appender=false,
 @ap_options={:multiline=>true},
 @filter=nil,
 @format=:color,
 @named_tags=nil,
 @processing=false,
 @quiet_assets=false,
 @rendered=false,
 @semantic=true,
 @started=false>
```
* Full Stack Trace, if an exception is being raised.

### Expected Behavior
When I've configured semantic logger with awesome_print's multiline option set to true, I expect the logs to appear multiline, roughly like so (screenshot from printing a hash with awesome_print in pry):
![Screenshot 2020-05-29 at 15 05 28](https://user-images.githubusercontent.com/3239252/83257839-da34b680-a1bd-11ea-95c4-4c54a275817c.png)

### Actual Behavior
Instead log entries appear on a single line:
![Screenshot 2020-05-29 at 15 06 11](https://user-images.githubusercontent.com/3239252/83257904-f3d5fe00-a1bd-11ea-9f75-864a751591ac.png)

Am I misunderstanding / do I have wrong expectations of the multiline option?

**Comment by reidmorrison** [comment]
To turn on multiline it must done within application.rb or the relevant env specific config file as follows:

**Comment by reidmorrison** [comment]
Since the awesome_print gem is dead, we switch to the amazing_print gem and it fixed all of our issues.
