### ISSUE TITLE
Any chance of a release with Amazing Print?

### ISSUE THREAD

**Issue by tomca32** [rocketjob/rails_semantic_logger#104]
I use Semantic Logger in all my projects, and absolutely love it.

I was just wondering if there's going to be a release soon with Amazing Print included? I see the `semantic_logger` was released but I don't see a `rails_semantic_logger` release. The deprecation messages are getting a bit annoying.

Thanks

**Comment by reidmorrison** [comment]
I don’t believe Rails Semantic Logger needs any changes to use Amazing Print.
Upgrade Semantic Logger and replace awesome_print with amazing_print in the Gemfile.

**Comment by tomca32** [comment]
Ah great, thanks for the help. I'll close the issue.
