### ISSUE TITLE
Tagged logging with semantic mode off

### ISSUE THREAD

**Issue by silasb** [rocketjob/rails_semantic_logger#107]
If I run with `config.rails_semantic_logger.semantic = false` my tagged logs look like:

```
2020-09-22 11:56:06.211185 D [95930:puma threadpool 001] [[[:request_id, :request_id], [:ip, :remote_ip] .....
```

I'm expecting to see them like this:

```
2020-09-22 12:24:30.390403 I [98415:puma threadpool 001] {user_id: ?, subdomain: , uuid: d7b8b167-621c-4482-9a3c-6c3e0385d077, user_agent: curl/7.64.1} ....
```

I can make this kind of work by modifying the `engine.rb` file like so:

```
        if defined?(Rails::Rack::Logger)
          config.middleware.swap(Rails::Rack::Logger, RailsSemanticLogger::Rack::Logger, config.log_tags)
        end
```

Which kind of works..... I get my tagged logs, but logging is slightly different.

```
[...] Rack -- Started -- { :method => "GET", :path => "/api", :ip => "::1" }
[...] Rails -- Processing by StaticPagesController#index as */*
[...] Rails --   Parameters: {"path"=>"api"}
...
```

Whereas with no code changes I'd get
```
[...] Rails -- Started GET "/api" for ::1 at 2020-09-22 12:28:53 -0400
[...] Rails -- Processing by StaticPagesController#index as */*
[...]  Rails --   Parameters: {"path"=>"api"}
...
```

It's pretty much the exact same messaging other than the "started" message for the request which now seems to be handled via Rack instead of Rails.

Since swapping out the middleware makes tagged logging work but changes the "started" messaging I'm wondering if we are connecting to the correct notification/instrumentation. I'm not 100% sure where the disconnect is.

My end goal is to provide all the niceties that SemanticLogger providers without using the semantic featured enabled, but also have tagged logging enabled.  We are finding with semantic mode enabled it's harder to quickly parse the logs.

**Comment by reidmorrison** [comment]
Have you considered using the Semantic Logger gem directly without using the horrible hacks that make up Rails Semantic Logger?

**Comment by reidmorrison** [comment]
Actually, that is what I would expect since Rails natively does not support hash / named tags. By turning off rails semantic logger the hash/named tags feature is also removed.
