### ISSUE TITLE
undefined method `current_tags' for nil:NilClass with Rails 5.0.0.beta3

### ISSUE THREAD

**Issue by xanview** [rocketjob/rails_semantic_logger#11]
I am getting this exception when trying to send an email:

```
UserMailer.password_reset(user).deliver_later
NoMethodError: undefined method `current_tags' for nil:NilClass
from /usr/local/lib/ruby/gems/2.3.0/gems/activejob-5.0.0.beta3/lib/active_job/logging.rb:51:in `logger_tagged_by_active_job?'
```

This didn't happen with beta1 and doesn't happen if I remove rails_semantic_logger.

Any ideas?

**Comment by reidmorrison** [comment]
Is this happening with Rails Semantic Logger v3.1? If not, please try 3.1 and let me know if it helps.

**Comment by reidmorrison** [comment]
Oh, just noticed they renamed the Active job method #tag to #tag_logger with the latest Beta release. Will make a change to support both the old and the new method names in case anyone else is still running Rails 5 Beta 2.

**Comment by reidmorrison** [comment]
Can you try the latest in master by changing the gem entry to:

~~~ruby
gem 'rails_semantic_logger', git: 'git@github.com:rocketjob/rails_semantic_logger.git'
~~~

If this works I can include it in the next Gem release.

**Comment by xanview** [comment]
That error disappeared and now I'm seeing this instead, hmmm:

```
2016-02-29 16:43:48.733438 E [95858:SemanticLogger::AppenderThread] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::File:0x007ff3e7a617f0 @log=#<IO:<STDOUT>>, @formatter=:default, @filter=nil, @name="SemanticLogger::Appender::File"> -- Exception: NoMethodError: undefined method `call' for :default:Symbol
Did you mean?  caller
               all
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.1.0/lib/semantic_logger/appender/file.rb:118:in `log'
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.1.0/lib/semantic_logger/logger.rb:174:in `block in appender_thread'
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.1.0/lib/semantic_logger/logger.rb:172:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.1.0/lib/semantic_logger/logger.rb:172:in `appender_thread'
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.1.0/lib/semantic_logger/logger.rb:148:in `block in start_appender_thread'
```

**Comment by reidmorrison** [comment]
Ah, I see. Colorized logging is disabled. 
`config.colorize_logging = false`

Please update `rails_semantic_logger` from master. Just pushed a fix to correctly handle when colorized logging is turned. 

Give colorized logging a try, it makes it easier to read the text logs.

If you do colorized logging, add the awesome-print gem before the `rails_semantic_logger` gem entry to create "pretty" log output:
`gem 'awesome_print'`

**Comment by xanview** [comment]
I can't see a change yet from adding awesome_print, but no more errors, thank you :D

**Comment by xanview** [comment]
It seems the error is back?

```ruby
timeline(dev)> UserMailer.password_reset(User.first).deliver_later
NoMethodError: undefined method `current_tags' for nil:NilClass
from /usr/local/lib/ruby/gems/2.3.0/gems/activejob-5.0.0.beta3/lib/active_job/logging.rb:51:in `logger_tagged_by_active_job?'
```

I'm using:

```ruby
gem 'rails_semantic_logger', git: 'git@github.com:rocketjob/rails_semantic_logger.git'
```

Any ideas?

**Comment by xanview** [comment]
Seems latest from git is working at the moment! Thank you!! :)

**Comment by reidmorrison** [comment]
Yes, and I also added a test so that it should not break again. 

Thank you for letting me know it was not working again.
