### ISSUE TITLE
No STDOUT logging by default.

### ISSUE THREAD

**Issue by misaka** [rocketjob/rails_semantic_logger#113]
### Environment

* Ruby Version: 2.7.2
* Rails Version: 6.0.3.4
* Semantic Logger Version: 4.7.4
* Rails Semantic Logger Version: 4.4.5
* Puma Version: 5.1.0
* Rack Version: 2.2.3
* Rails configuration: Rails being run in dev environment without any special configuration (semantic logger initialiser commented out and no other known logging configuration present).

### Expected Behavior

When running Rails server I expect to see see logs on STDOUT by default. i.e. without having to add my own appender.

### Actual Behavior

No logs are produced on STDOUT when running Rails server unless I add my own log appender.

This used to work on v4.4.4. After some investigation it becomes apparent that `Rails::Server#log_to_stdout` is being called before it can be patched by `rails_semantic_logger/extensions/rails/server.rb`, implying that this extension is being loaded too late in the Rails startup process. The way this file is loaded appears to have been changed in #106.

This issue has been confirmed on a fresh Rails project (same versions as above), steps to reproduce:

1. Create new Rails project
2. Add `rails_semantic_logger`.
3. Start Rails server in terminal.
3. Navigate to http://localhost:3000/.
4. Note lack of logs in terminal.

### Pull Request

https://github.com/rocketjob/rails_semantic_logger/pull/114

**Comment by reidmorrison** [comment]
Reverted log disabling pull request to restore std out logging. Fixed in v4.4.6
