### ISSUE TITLE
Hiding semantic message conversion for Controller

### ISSUE THREAD

**Issue by s1monj** [rocketjob/rails_semantic_logger#119]
This gem is great thanks! I have a small issue where I can't hide the "Completed" Controller output after a controller is called

```
ruby v2.6.3
rails v5.2.0
semantic_logger 4.4
rails_semantic_logger 4.4.6

config.log_level = :info
config.rails_semantic_logger.format = :json
config.paths['log'] = 'log/application_log.json'
config.rails_semantic_logger.quiet_assets = true
config.assets.quiet = true
```
produces the following "Completed" message after each controller call:
```
{"application":"Semantic Logger", "name":"EntitiesController", "message":"Completed #my_action","payload": {"controller":"MyController","action":"my_action","params": ...
```
So following instructions [here](https://github.com/rocketjob/semantic_logger/blob/master/docs/rails.md#semantic-log-output) I added:
```
 config.rails_semantic_logger.semantic = false
```
Which correctly removed that specific "Completed" message above but added many more extra messages:
```
{"application":"Semantic Logger","name":"Rails","message":"Started GET for 127.0.0.1 at 2021-01-18 22:21:42 -0500"}
{"application":"Semantic Logger","name":"Rails","message":"Processing by MyController#my_action as JSON"}
{"application":"Semantic Logger","name":"Rails","message":"Parameters: ...
{"application":"Semantic Logger","name":"Rails", "message":"Completed 200 OK in 197ms (Views: 1.4ms | ActiveRecord: 57.3ms)"...
```
So then I tried to add this as well:
```
config.rails_semantic_logger.started    = false
config.rails_semantic_logger.processing = false
config.rails_semantic_logger.rendered   = false
```
But it doesn't appear to have any effect and I am left with more verbose logs than what I started with.

Is there any way I can hide all of these automatic Controller/Rails log lines above?

**Comment by reidmorrison** [comment]
Rails Semantic Logger is designed to log at least one log entry for every web request, turning off the Completed message would result in no output for a web request. For this unique use-case the best way to do it would be to add a filter that filters out messages from the Rails class that start with "Completed".

Something like:
~~~ruby
config.rails_semantic_logger.filter = -> log { log.name == "Rails" && log.message.start_with?("Completed") }
~~~
