### ISSUE TITLE
Can't disable started, processing and rendered logs when using log_level debug

### ISSUE THREAD

**Issue by yourivdlans** [rocketjob/rails_semantic_logger#125]
### Environment
* Ruby Version: 2.6.6
* Rails Version: 6.0.3.2
* Semantic Logger Version: 4.7.4
* Rails Semantic Logger Version: 4.5.0
* Puma: 4.3.6
* Rails configuration:
```rb
config.log_level = :debug
STDOUT.sync = true
config.rails_semantic_logger.rendered = false
config.rails_semantic_logger.add_file_appender = false
config.semantic_logger.add_appender(io: STDOUT, level: config.log_level, formatter: config.rails_semantic_logger.format)
```

### Expected Behavior
Using above configuration I should not see the ActionView rendered output, but I am.

### Actual Behavior
I am still seeing the rendered logs being output, same goes for the started and processing logs (These are disabled by default as well).

It seems when I set the `log_level` to `:info` the `started`, `processing` and `rendered` config settings do take effect.

**Comment by andrew-newell** [comment]
I believe this is the offending line for the "Processing" log, 
https://github.com/rocketjob/rails_semantic_logger/blob/47112b2c9effe7ab72f4f99d46875ed8d67d0965/lib/rails_semantic_logger/action_controller/log_subscriber.rb#L8
which has a comment: ` # Log as debug to hide Processing messages in production`

As far as the other "started" and "rendered" logs, you can set their log level using:
```ruby
RailsSemanticLogger::Rack::Logger.started_request_log_level = :trace
RailsSemanticLogger::ActionView::LogSubscriber.rendered_log_level = :trace
```

**Comment by yourivdlans** [comment]
@andrew-newell Thanks! In the end I chose to go with another gem because this didn't feel like the best solution for our problem.
