### ISSUE TITLE
uninitialized constant SemanticLogger::Subscriber (NameError)

### ISSUE THREAD

**Issue by timuckun** [rocketjob/rails_semantic_logger#13]
I get the following error when attempting to define a new appender.

db_log_appender.rb:3:in `<top (required)>': uninitialized constant SemanticLogger::Subscriber (NameError)

I changed it to  SemanticLogger::Appender::Base and it stopped erring but I don't understand why.  The sample code says to inherit from Subscriber.

Is there something else I should be doing?

**Comment by timuckun** [comment]
This is because the documentation for semantic logger is for version 3.3 but the 3.3 gem is not published yet and this gem is using 3.1

**Comment by reidmorrison** [comment]
Correct, I pushed the documentation before the gem was ready. I will hold off on pushing the updated docs again until the gem is published.

Please upgrade both rails_semantic_logger and semantic_logger to the newly published v3.3 gems.
It will resolve the error above.
