### ISSUE TITLE
Extra blank log messages in development for asset GETs

### ISSUE THREAD

**Issue by ibrahima** [rocketjob/rails_semantic_logger#15]
Hi, I've been looking into semantic_logger for formatting logs for Logstash, and it looks pretty nice overall! Really like the threaded design to avoid logging slowing down the application. I just noticed something strange in development though; each GET for an asset has a bunch of extra blank lines, which is kind of annoying. I actually think that in production Rails still defaults to `log_level = :debug` so it seems like this would show up there too?

Example log output:

`2016-04-11 19:26:50.958934 D [4403:47051589538600] Rails -- Started GET "/assets/application.css" for 10.0.3.1 at 2016-04-11 19:26:50 +0000
2016-04-11 19:26:50.982768 D [4403:47051589538600] Rails -- 
2016-04-11 19:26:50.982815 D [4403:47051589538600] Rails -- 
`

As you can see, there are two extra lines for the GET that are completely blank. This happens for eac GET. Disabling semantic_logger removes these lines, and interestingly, setting `config.rails_semantic_logger.semantic = false` still results in this output (i.e., the output above is with semantic disabled).

This seems like a poor interaction with some other part of my infrastructure, but not sure what it could be. We're using unicorn as our development and production server, Rails 4.2.6, Sprockets 3.52, etc. Any ideas? Thanks!

**Comment by reidmorrison** [comment]
Yes, the 2 blank lines are output by rails at development level. I believe they are removed in Rails 5.

Try adding the following lines to `config/environments/production.rb`:
~~~ruby
  config.log_level = :info
  config.colorize_logging = true
~~~

**Comment by llaurent** [comment]
in the mean time you could also register a filter and filter out empty messages.

**Comment by reidmorrison** [comment]
Excellent idea. The following filter will strip all blank messages from the Rails logger:

~~~ruby
Rails.logger.filter = -> log { log.message.present? || log.payload.present? }
~~~
