### ISSUE TITLE
Semantic info isn't being added to Rails 5 payloads

### ISSUE THREAD

**Issue by zach-taylor** [rocketjob/rails_semantic_logger#16]
Rails version: 5.0.0.beta3

In my Rails 5 application, I don't seem to be getting the semantic behavior of this library (e.g. the format, runtimes, status_message, etc) on "completed" logs. The logs are still being formatted correctly, it just seems to be missing some information:

```json
{
  "name": "Rails",
  "pid": 10,
  "thread": "70187985393180",
  "level": "info",
  "level_index": 2,
  "host": "33e8208f-a23a-44e3-8e51-ad97fec62806",
  "application": "SSO",
  "tags": [
    "001d4663-2784-443e-8970-ba154ed3d24c"
  ],
  "message": "Completed 302 Found in 117ms (ActiveRecord: 0.0ms)",
  "timestamp": "2016-04-19T14:04:17.974534Z"
}
```
This is with the `rails_semantic_logger` included in my Gemfile, with no other configuration. No `awesome_print` included as well.

**Comment by reidmorrison** [comment]
Appears to be related to Rails 5 trying to support regular Rails apps and API only apps.
Adding the following line to application.rb solves the problem:

~~~ruby
require 'action_controller/log_subscriber'
~~~

Not sure if this is something we want to automatically do as part of Rails Semantic logger?
