### ISSUE TITLE
Tagged logging?

### ISSUE THREAD

**Issue by magicalbanana** [rocketjob/rails_semantic_logger#18]
How do you set this up if you want your logs to be tagged by default without using a block?

**Comment by reidmorrison** [comment]
To add tags per thread without a block:
http://www.rubydoc.info/gems/semantic_logger/SemanticLogger#push_tags-class_method

Then to remove added tags:
http://www.rubydoc.info/gems/semantic_logger/SemanticLogger#pop_tags-class_method

Or if you want to add tags to every rails web request use the rails mechanism configured using `config.log_tags`. For example:
~~~ruby
config.log_tags = [ :remote_ip ]
~~~

**Comment by magicalbanana** [comment]
I tried that but I still can't see the tags. I'm trying to setup the logger to output similar to this example where it's outputting `[jbloggs]`.

https://rocketjob.github.io/semantic_logger/rails.html

**Comment by reidmorrison** [comment]
Were you able to get it working?
