### ISSUE TITLE
Better formatting options for ActiveRecord::Base?

### ISSUE THREAD

**Issue by thom-nic** [rocketjob/rails_semantic_logger#21]
_(moved from rocketjob/semantic_logger#32)_

In semantic_logger v1.8 I had logging output that looked like this (with a custom formatter):
<img width="1132" alt="screen shot 2016-08-01 at 5 20 23 pm" src="https://cloud.githubusercontent.com/assets/95562/17314787/d100f46a-5834-11e6-833d-13e412d7f8b1.png">

I just upgraded to v3.3 and the same formatter (adapted to new AwesomePrint format) looks like this:
<img width="1133" alt="screen shot 2016-08-01 at 10 12 38 pm" src="https://cloud.githubusercontent.com/assets/95562/17314837/33ef8460-5835-11e6-925e-39c834f47bad.png">

Unfortunately, the 'payload' portion of the log feels like a step backwards.  Any way to get the old log formatting back?

**Comment by thom-nic** [comment]
I see [this line in engine.rb](https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/engine.rb#L162) which looks like it should be doing what I want however it's clearly not...  

I noticed the `config.before_initialize` block so I tried moving some config from config/initializers to config/environments however that doesn't seem to help any.  Also tried disabling my custom formatter entirely however I still see an ugly hash with lots of escaped double quotes from all of the ActiveRecord::Base log output.

**Comment by thom-nic** [comment]
Also should mention I'm using rails v4.2.5.1

**Comment by thom-nic** [comment]
I think I see what I need to do now, to get the old behavior I needed to set `config.rails_semantic_logger.semantic   = false` in config/environments so Rails SemanticLogger doesn't override the default ActiveRecord logger with the one that generates the hash.

**Comment by reidmorrison** [comment]
Glad you were able to find the option to get the appropriate level of semantic translation for rails logs that meets your needs.
