### ISSUE TITLE
Messages not logging in one environment but are in another

### ISSUE THREAD

**Issue by ericgross** [rocketjob/rails_semantic_logger#27]
I have an application with multiple environments in Heroku. Both of them use the `production` rails environment. I have a Sidekiq job that starts like this:

```
module Workers
  module Slack
    class NewOrders
      include Sidekiq::Worker
      include SemanticLogger::Loggable
      extend Memoist

      def initialize
        @slack_client = default_slack_client
      end

      # :reek:ControlParameter
      def perform(client: nil)
        logger.info "Checking for new orders since #{since} ..."
        @slack_client = client if client
        send_notifications(since: since)
        update_last_query_time
      end

```

In one environment (`staging`), I see the output in the Heroku logs. However, in the other environment (`production`), I am not seeing the output.

I have confirmed that my `default_level` is set to `:trace` in both environments. Here is my initializer:

```
require 'semantic_logger'

SemanticLogger.default_level = :trace
SemanticLogger.add_appender(io: $stdout) if Figaro.env.heroku_app_name

```

How come the logs are not appearing in production?

**Comment by reidmorrison** [comment]
If you are running Rails it is recommended to use the `rails_semantic_logger` gem to take care of logging connectivity.

In the above code the if statement should be removed if you want to log output to stdout. If it returns false there will not be any logging.

**Comment by reidmorrison** [comment]
Please re-open the ticket with further information, or post questions in the gitter support channel  if you are still experiencing difficulties.
