### ISSUE TITLE
Docs: Disabling default appender

### ISSUE THREAD

**Issue by aldhsu** [rocketjob/rails_semantic_logger#30]
In the docs:
> When running in an environment where local file logging is not available, or to completely replace the file logger, disable the default rails file logging by setting:
`config.rails_semantic_logger.add_file_appender = true`

I believe this is supposed to be:
`config.rails_semantic_logger.add_file_appender = false`

**Comment by reidmorrison** [comment]
Good catch, want to submit a pull request against the gh-pages branch with this fix?

**Comment by reidmorrison** [comment]
Fixed with https://github.com/rocketjob/semantic_logger/commit/77679f1b1e9c16c7ac2825cae9e17846deaeb59a

Thank you for the feedback.
