### ISSUE TITLE
Problem with Rails 5.1 and ruby 2.4.1

### ISSUE THREAD

**Issue by igortice** [rocketjob/rails_semantic_logger#31]
E [24050:puma 002 log_subscriber.rb:85] ActiveRecord::Base -- Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 1, expected 2)

**Comment by reidmorrison** [comment]
Will include the fix above in the next gem. Please re-open if you see any issues after that.

**Comment by reidmorrison** [comment]
Gem v4.0.1 has been released with the above patch.

**Comment by igortice** [comment]
thank's, it's perfect now.
