### ISSUE TITLE
Semantic logger throws error ( Could not log \"sql.active_record\" event. NameError: uninitialized constant ) while logging sql queries

### ISSUE THREAD

**Issue by robinson-ih** [rocketjob/rails_semantic_logger#42]
### Environment
* Ruby Version - 2.1.7
* Rails Version - 3.2.22
* Semantic Logger Version - 3.3
* Rails Semantic Logger Version - 3.4.1

Note:
* While logging SQL queries in the log file using rails semantic logger with below option `config.rails_semantic_logger.semantic = true` it throws an error. It is happening whenever the application hits the database and tries to log the SQL queries. 

 `{"name":"ActiveRecord::Base","pid":3125,"thread":"70305435605980","level":"error","level_index":4,"host":"MacBook-Pro.local","application":"Semantic Logger","file":"/Users/sampleuser/.rvm/gems/ruby-2.1.7@sample/gems/activesupport-3.2.22.5/lib/active_support/log_subscriber.rb","line":95,"message":"Could not log \"sql.active_record\" event. NameError: uninitialized constant`

ERROR -- : Could not log "sql.active_record" event. NameError: uninitialized constant ActiveRecord::LogSubscriber::IGNORE_PAYLOAD_NAMES

Please help me to resolve to move forward

**Comment by mike-stewart** [comment]
It seems that version 3.4.x of this gem is not fully compatible with Rails 3.2. 

The error is occuring [in the ActiveRecord#LogSubscriber extension](https://github.com/rocketjob/rails_semantic_logger/blob/v3.4.1/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb#L11), which references a constant that's only present in Rails 4+. Ref: [Rails 3.2 version](https://github.com/rails/rails/blob/v3.2.22.5/activerecord/lib/active_record/log_subscriber.rb#L2) and [Rails.5.1 version](https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/log_subscriber.rb#L3).

It's a simple fix. I've patched it in my fork - https://github.com/mike-stewart/rails_semantic_logger/commit/60d0d6c9ff960bd056daec6b07b7b50eeec06419. @reidmorrison Would you be open to a PR to release a patched 3.4.2 version?

**Comment by reidmorrison** [comment]
Yes please, I am sure their are other users that would benefit from the patch.
Rather than expanding the constant that could impact forward compatibility, consider defining the constant if it is not already defined:
~~~ruby
# Support Rails 3.2
IGNORE_PAYLOAD_NAMES=['SCHEMA', 'EXPLAIN'] unless defined?(IGNORE_PAYLOAD_NAMES)
~~~

**Comment by mike-stewart** [comment]
@reidmorrison I found one other issue with Rails 3.2 compatibility - specifically LogSubscriber#render_bind being undefined. My fork seems to be working fine on Rails 3.2 now - would you be open to a PR to create a 3.4.2 version of this gem?

I think you would need to create a branch from 3.4.1 for me to create the PR against.

Here's the diff: https://github.com/rocketjob/rails_semantic_logger/compare/master...mike-stewart:rails-3-2

**Comment by reidmorrison** [comment]
The diff looks great, would be happy to pull in a PR to help Rails 3.2 support.

With so many people sending fixes for Rails 3.2, maybe we need to add back official support for Rails 3.2. Strangely the hardest part is creating a Rails 3.2 dummy rails app to run the tests in.

**Comment by mike-stewart** [comment]
Where do you want me to target the PR? Presumably it can't be targeted to master, as the current 4.x release series doesn't have 3.2 support. Will you be releasing a new 3.4.x release?

Curious, what's the difficulty in creating a Rails 3.2 dummy app?

**Comment by reidmorrison** [comment]
The `master` branch will be great.

The challenge is getting Travis to run both of the Rails dummy apps, the current one for Rails 4 and 5, then switching to a different test dummy rails app to run the Rails 3.2 tests.

If you want to take the time to create the Rails 3.2 app and figure out getting Travis tests running, then we can add back official support for Rails 3.2.

As a side note, are you upgrading to Rails Semantic Logger v3.4 to get the latest features? The earlier versions should work fine with Rails 3.2 and the latest Semantic Logger.

**Comment by mike-stewart** [comment]
Sure, I'll create a PR. I was using 3.4 as that is the latest version that supports Rails 3.2 according to your gemspec.

**Comment by reidmorrison** [comment]
@robinson-ih can you try the master branch?

**Comment by arianf** [comment]
@reidmorrison Hi Reid, I know Rails 3.2 isn't officially supported by Rails Semantic Logger or the Rails team... the pull request that @mike-stewart made went into master, but it didn't go into `3.4.1` (the last version that supports `3.2`).

What's the point of adding this pull request: https://github.com/rocketjob/rails_semantic_logger/pull/44 (Add Rails 3.2 Support) if it only goes into `4.x.x` which doesn't even support Rails 3.2

Would it be possible to create a new rails_semantic_logger version `3.4.2` that includes the changes from the pull request: https://github.com/rocketjob/rails_semantic_logger/pull/44
