### ISSUE TITLE
status and status_message not recorded for Devise non 200 response?

### ISSUE THREAD

**Issue by mattscilipoti** [rocketjob/rails_semantic_logger#46]
### Environment

- ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
- rails-5.0.5
- semantic_logger-4.2.0
- rails_semantic_logger-4.1.3
- puma-3.8.2

- no semantic_logger configuration changes

### Expected Behavior

- Request log entry should include status and status_message. Like this:

```
Devise::SessionsController -- Completed #new -- { :controller => "Devise::SessionsController", :action => "new", 
:format => "HTML", 
:method => "GET", 
:path => "/devise_users/sign_in", 
:status => 200, 
:view_runtime => 1598.92, 
:db_runtime => 3.59, 
:status_message => "OK" }
```

### Actual Behavior

When controller response is 401 (due to failed before_action), the status and status_message are NOT recorded:
```
MiscPagesController -- Completed #terms_and_conditions -- { :controller => "MiscPagesController", :action => "terms_and_conditions", 
:format => "HTML", 
:method => "GET", 
:path => "/terms", 
:view_runtime => 0.0, 
:db_runtime => 0.0 }
```

Note: this 401 is due to Devise's `before_action :authenticate_user!`

**Comment by reidmorrison** [comment]
Can you submit a PR once you have resolved this issue locally?

**Comment by reidmorrison** [comment]
Devise chose to override a Rails method that maps processing times to a string for logging purposes to now set the status code. The string mapping is not used or needed when performing Semantic logging.

The Devise hack to set the 401 status code:
~~~ruby
def log_process_action(payload)
  payload[:status] ||= 401 unless payload[:exception]
  super
end
~~~

As a workaround special code will be added to the Rails patch to call this method and discard any result.
