### ISSUE TITLE
Messages are being logged although logger is disabled

### ISSUE THREAD

**Issue by aurelian** [rocketjob/rails_semantic_logger#48]
### Environment

* Ruby Version: 2.4.x
* Rails Version. 4.2.x
* Semantic Logger Version. 4.1
* Rails Semantic Logger Version. 4.1.3
* Other Application/framework names and versions (e.g. Puma, etc.) unicorn
* Rails configuration: `config.action_mailer.logger = nil`

Basically if I set `config.action_mailer.logger = nil` I expect messages not to be logged at all.

### Expected Behavior

Should not log messages if logging is disabled in app config 👌 

### Actual Behavior

Messages are being logged 😢

**Comment by reidmorrison** [comment]
To change a logger instance so that it’s log messages do not show up, raise its log level beyond the current global level, for example :trace:

   ActionMailer.logger.level = :trace

**Comment by aurelian** [comment]
Hi @reidmorrison ! Thanks, I understand, probably it will work.

`config.action_mailer.logger = nil` is a Rails configuration where you tell the framework not to log certain messages coming from a certain framework.

[Here's the rails guide about this config](http://guides.rubyonrails.org/configuring.html#configuring-action-mailer):

> config.action_mailer.logger accepts a logger conforming to the interface of Log4r or the default Ruby Logger class, which is then used to log information from Action Mailer. Set to nil to disable logging.

rails_semantic_logger ignores this configuration and sets it to something else than `nil`, thus logging the messages.

This info should be added to the documentation somehow.
