### ISSUE TITLE
Usage on Heroku to get STDOUT logging: here's what I did

### ISSUE THREAD

**Issue by bf4** [rocketjob/rails_semantic_logger#53]
### Environment

| what | value|
|-------|--------|
| Ruby Version | 2.3
| Rails Version | 4.2.7
| Semantic Logger Version | 4.2.0
| Rails Semantic Logger Version | 4.1.3
| Puma | 3.9.1

My config as described in

```ruby
 # per rails_12factor, example of ussing ENV var to need for rails_stdout_logging
    # On Heroku, config:set RAILS_LOG_TO_STDOUT=true
    if ENV["RAILS_LOG_TO_STDOUT"].present?
      # turn off file logging
      config.rails_semantic_logger.add_file_appender = false
      # configure logging to STDOUT like rails_stdout_logging (i.e. 'io: STDOUT' and 'STDOUT.sync = true')
      config.semantic_logger.add_appender(io: STDOUT, level: config.log_level, formatter: config.rails_semantic_logger.format)
      STDOUT.sync = true
    end
```

additional config if still using rails_12factor or rails_stdout_logging

```ruby
  fail "remove the block which overrides the RailsStdoutLogging override" unless defined?(RailsStdoutLogging)
  initializer(:override_rails_stdout_logging_logger, after: :rails_stdout_logging) do
    ::Rails.logger = config.logger = SemanticLogger[Rails]
  end
```

Results in  logs which Heroku prints as:

```
2017-12-19T20:45:43.067591+00:00 app[scheduler.7507]: 2017-12-19T20:45:43.067183Z I [4:70005105193240] Rails -- [SKYLIGHT] [1.4.2] Skylight agent enabled -- {:pid=>4}
```

### Expected Behavior vs. Actual Behavior

I expected dropping in rails_semantic_logger would be enough. 

However, rails_stdout_logger was still setting the logger in production.  I override its initializer to get over that.

But now nothing was being logged because, and I'm guessing, the default file appender was trying to log to a file.  Since there's no Rails-level config I see for telling it to use the `STDOUT` device, even though it takes an `io` option, I had to write my own config, which I'm not sharing.

This took quite a bit of docs and code reading, and I would have thought someone else had tried this, or that there'd even be a 'plugin'.  I'm happy to have that discussion here or in the other repo, or make a PR if this looks like I'm using the gem correctly.

Also, while here, I wanted to show how I added some default params to the payload using a module, since it was unclear if log tags could/should do that.

```ruby
    # Extend logging formatter: default
    config.rails_semantic_logger.format = :default
    SemanticLogger::Formatters::Default.prepend ::LoggingFormater

module LoggingFormatter
    # Default time format is ISO8601
    def initialize(time_format: :iso_8601, log_host: true, log_application: true)
      super(time_format: time_format, log_host: log_host, log_application: log_application)
    end

    def payload
      log.payload ||= {}
      log.payload[:pid] = Process.pid
      super
    end
end
```

**Comment by rforte** [comment]
@bf4 I'm actually working through the same issue this afternoon. I'm currently reading the source and stepping through code to figure out what the most minimal setup is needed to get the semantic_logger working on Heroku (which I'm shocked appears no one else has done before). I will post back here on what I find. Is there a reason you're choosing not to share your config? 

Cheers

**Comment by bf4** [comment]
@rforte 

>  Is there a reason you're choosing not to share your config 

I actually don't recall what I meant by that since I obviously was including what I had done. Maybe I meant https://github.com/heroku/rails_12factor/issues/27#issuecomment-352968577 ?

In the end, I noticed since I no longer was logging requests with semantic logger, it with lograge.

my `config/application.rb`

```diff
-    # Extend logging formatter: default
-    config.rails_semantic_logger.format = :default
-    SemanticLogger::Formatters::Default.prepend ::::LoggingFormatter
-    # per rails_12factor, example of using ENV var to need for rails_stdout_logging
+
+    config.lograge.enabled = true
+    config.lograge.base_controller_class = 'ApplicationController'
+    config.lograge.custom_options = lambda do |event|
+      {
+        pid: Process.pid,
+        time: event.time.utc.iso8601(6)
+      }
+    end
+    config.lograge.custom_payload do |controller|
+      filter_parameters = Rails.configuration.filter_parameters
+      filter_params_regex = Regexp.union filter_parameters.map {|filter_param| /(?<key>#{filter_param})=[^&$]*/ }
+      params_filter = ActionDispatch::Http::ParameterFilter.new(filter_parameters)
+      {
+        dyno: ENV[-'PS'] || ENV[-'DYNO'] || (defined?(Rails::Console) ? -"console" : -""),
+        request_host: controller.request.host,
+        request_protocol: controller.request.protocol,
+        request_remote_ip: controller.request.remote_ip,
+        request_trace_id: controller.request.uuid,
+        request_params: params_filter.filter(controller.request.query_parameters),
+        request_body_params: params_filter.filter(controller.request.request_parameters),
+        request_referrer: (referrer = controller.request.referer) && referrer.gsub(filter_params_regex)  { -"#{Regexp.last_match[:key]}=FILTERED" },
+        request_user_agent:  controller.request.user_agent,
+        request_format: controller.request.format.to_s,
+        request_content_type: controller.request.content_type,
+        request_accept: controller.request.env[-'HTTP_ACCEPT'],
+        session_current_user_id: controller.current_user&.id,
+        response_content_type: controller.response.content_type
+      }
+    end
+    config.log_formatter = config.lograge.formatter
    # On Heroku, RAILS_LOG_TO_STDOUT=true
+    # configure logging to STDOUT like rails_stdout_logging (i.e. 'io: STDOUT' and 'STDOUT.sync = true')
     if ENV["RAILS_LOG_TO_STDOUT"].present?
-      # turn off file logging
-      config.rails_semantic_logger.add_file_appender = false
-      # configure logging to STDOUT like rails_stdout_logging (i.e. 'io: STDOUT' and 'STDOUT.sync = true')
-      config.semantic_logger.add_appender(io: STDOUT, level: config.log_level, formatter: config.rails_semantic_logger.format)
-      STDOUT.sync = true
+      initializer(:app_stdout_logging, before: :initialize_logger) do
+        logger           = ActiveSupport::Logger.new(STDOUT)
+        logger.formatter = config.log_formatter
+        logger.level = config.log_level
+        logger = ActiveSupport::TaggedLogging.new(logger)
+        ::Rails.logger = config.logger = logger
+        # Disable double loggging https://github.com/heroku/rails_12factor/issues/27#issuecomment-352968577
+        if defined?(Rails::Console)
+          ActiveSupport::Logger.class_eval do
+            def self.broadcast(logger)
+              puts "logger broadcast disabled: #{logger.inspect}"
+              Module.new do end
+            end
+          end
+        end
+      end
```

( ref https://github.com/heroku/rails_12factor/issues/27#issuecomment-352968577 )

**Comment by reidmorrison** [comment]
Thank you @bf4, I added the info to the documentation for Heroku stdout setup.

As for the custom format, there is a section in the docs on writing custom formatters so that all log entries are modified to include global settings http://rocketjob.github.io/semantic_logger/customize.html

Or is this something more similar to `config.lograge.custom_payload` where custom data can be added to log entries only when a controller action is called?

To add any data to a controller action, using the Rails method below supports custom fields for all controllers when made in ApplicationController, or specific data when added to each controller:

~~~ruby
class ApplicationController < ActionController::Base
  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
  end
end
~~~

Once added to the payload it should show up automatically in the logs.

**Comment by bf4** [comment]
@reidmorrison Hiya and thanks for looking

re: adding the info to the documentation for Heroku stdout setup.

Not sure if that is a good idea since ultimately it ate my logs, which is why I moved away from semantic logger.  I'm not sure what it is about the design of the semantic logger that makes setting the log device to stdout to be so fraught.

Like, if I wanted to do something like `Rails.logger = ...` I'm not sure how I'd do that with semantic logger (after much source and docs reading at the time).  I wound up with `config.semantic_logger.add_appender(io: STDOUT, level: config.log_level, formatter: config.rails_semantic_logger.format)` but I'm sure I tried other things.  STDOUT is notably missing from the list of `Logging Destinations` in the docs (though it looks screen you may mean stdout or tty).

I probably tried something like

```ruby
SemanticLogger.add_appender(io: STDOUT, formatter: :default)
logger = SemanticLogger['ProgName']
logger.info "testing"
```

re: custom format do you mean how I prepended the module?

re: `config.lograge.custom_payload` it is one of the ways of appending info the payload. Of course the standard `append_info_to_payload` is available but I chose to just do it all in one spot in the config because I could :)

**Comment by bf4** [comment]
Ok
