### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by ZavyalovAndrey** [rocketjob/rails_semantic_logger#55]
### Environment
* Ruby Version 2.4.1
* Rails Version 5.1.5
* Semantic Logger Version 4.2.0
* Rails Semantic Logger Version 4.2.0

Note:
Only one parameter is expected: 
https://github.com/rails/rails/blob/v5.1.5/activerecord/lib/active_record/log_subscriber.rb#L45

But we pass two:
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb#L33

**Comment by joker-777** [comment]
We have the same problem!

**Comment by mordaroso** [comment]
I added a pull request with a fix that works for me. See https://github.com/rocketjob/rails_semantic_logger/pull/57

**Comment by reidmorrison** [comment]
Thank you @mordaroso. Will push a new gem shortly.

**Comment by joker-777** [comment]
@reidmorrison Thanks for merging this PR. Can you already estimate when you will bump a new version?

**Comment by gingerlime** [comment]
@reidmorrison hope I'm not nagging, but is there anything we can do to help get the gem pushed? (we can use git master in our Gemfile, but it feels a bit dirty. We therefore hope this can go out officially).
