### ISSUE TITLE
Log tags hash gets serialized instead of appended into log output

### ISSUE THREAD

**Issue by tomca32** [rocketjob/rails_semantic_logger#68]
### Environment

Ruby: `2.5.1`, `2.4.3`
Rails: `5.1.6`, `5.1.5`
Rails Semantic Logger: `4.2.1`
Puma: `3.11.3`

application.rb config:
```ruby
config.log_level = :info

config.log_tags = {
    request_id: :request_id,
    ip:         :remote_ip,
    user:       -> request { request.cookie_jar['login'] }
}

config.rails_semantic_logger.semantic   = true
config.rails_semantic_logger.started    = false
config.rails_semantic_logger.processing = false
config.rails_semantic_logger.rendered   = false
```

### Expected Behavior

Using the configuration above, I would expect the log tags to be appended to the log output.

### Actual Behavior

Seems that the `log_tags` hash just gets serialized via `to_s` and prepended to the log output.
```
2018-04-08 14:44:17.288342 I [98222:puma 004] [[[:request_id, :request_id], [:ip, :remote_ip], [:user, #<Proc:0x00007fa40d7e0a50@/Users/tpesut/mindleaps/tracker/config/application.rb:41 (lambda)>]]] (239.9ms) StudentsController -- Completed #show -- { :controller => "StudentsController", :action => "show", :params => { "id" => "204" }, :format => "HTML", :method => "GET", :path => "/students/204", :status => 200, :view_runtime => 216.52, :rendered_format => :html, :variant => [], :db_runtime => 3.17, :status_message => "OK" }
```

This is in line with the default Rails `log_tags` configuration, since it really expects an array of symbols that correspond to request methods and everything else gets serialized; however, since Semantic logger specifically mentions the `log_tags` hash in the documentation, I would expect it to behave differently.

**Comment by reidmorrison** [comment]
Changes have been made in master to replace several builtin Rails subscribers instead of patching them. It should help with the ongoing patching issues and loading order.
Give master a try locally and let us know if you run into any issues.

**Comment by reidmorrison** [comment]
Reproduced and fixed in master. Once we get confirmations that master is working for everyone, we will publish a new gem.

**Comment by tomca32** [comment]
Thanks for your work on this. Works great now.

**Comment by Daniel-ltw** [comment]
Is this resolved? 

I am trying 4.3.1 and it seems that I can't see the named_tags in the json output.
