### ISSUE TITLE
Not compatible with ActiveJob in Rails 4.2

### ISSUE THREAD

**Issue by johnathanludwig** [rocketjob/rails_semantic_logger#7]
While testing upgrading an app to Rails 4.2, I came across some logger related errors when using ActiveJob.

Trying to use the `deliver_later` method on a mailer with active job throws an error on this line: https://github.com/rails/rails/blob/master/activejob/lib/active_job/logging.rb#L50

The error thrown is undefined method `current_tags` for nil.

**Comment by reidmorrison** [comment]
Fundamentally Rails assumes there is only one logger and therefore one formatter. In SemanticLogger the formatting is done by each appender and not the logger itself.
Would be so much easier if Rails just adopted SemanticLogger as its logging framework.
Suspect this is going to have to be another monkey-patch on the Rails code to change its behavior.
