### ISSUE TITLE
Rails Semantic Logger overwrites formatters for existing appenders

### ISSUE THREAD

**Issue by qstearns** [rocketjob/rails_semantic_logger#73]
### Environment

You can see an example project here:
https://github.com/qstearns/logging_proj

I am on:
* Ruby: 2.3.1
* Rails: 5.2.0
* Semantic Logger: 4.3.0
* Rails Semantic Logger: 4.3.1

This issue can be reproduced with a vanilla Rails project.
### Expected Behavior

I am trying to set up an additional appender for Semantic Logger with a json formatter in this line:

https://github.com/qstearns/logging_proj/blob/master/config/application.rb#L19-L22

I also want to continue to use the default appender provided by Rails Semantic Logger. For this reason, I leave `config.rails_semantic_logger.add_appender` at the default of true.

I'm expecting to produce one log at `log/a_json_log.json` that is formatted as json and a second log at `log/#{RAILS_ENV}_log.log` that's formatted with the default Rails logger.

You can start a Rails server in the provided project and hit the index page while running both `tail -f log/a_json_log.json` and `tail -f log/development.log` from the project root to observe this issue.

### Actual Behavior

Unfortunately, both logs log with the default rails formatting ie.  `log/a_json_log.json` looks like this:

```
2018-06-27 09:02:22.613134 D [87247:puma 004] Rack -- Started -- {:method=>"GET", :path=>"/", :ip=>"127.0.0.1"}
2018-06-27 09:02:22.815406 D [87247:puma 004] Rails::WelcomeController -- Processing #index
2018-06-27 09:02:22.833307 D [87247:puma 004] ActionView -- Rendering -- {:template=>"/Users/qstear/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.0/lib/rails/templates/rails/welcome/index.html.erb"}
2018-06-27 09:02:22.838151 D [87247:puma 004] (4.747ms) ActionView -- Rendered -- {:template=>"/Users/qstear/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.0/lib/rails/templates/rails/welcome/index.html.erb"}
2018-06-27 09:02:22.838412 I [87247:puma 004] (22.9ms) Rails::WelcomeController -- Completed #index -- {:controller=>"Rails::WelcomeController", :action=>"index", :format=>"HTML", :method=>"GET", :path=>"/", :status=>200, :view_runtime=>12.32, :db_runtime=>0.0, :status_message=>"OK"}
```

I believe the problem is on this line where Rails Semantic Logger overwrites the formatters for all existing file appenders:

https://github.com/rocketjob/rails_semantic_logger/blob/7b07eb6e89dbd1ea8b56e4b1b4308de4fa284c41/lib/rails_semantic_logger/engine.rb#L149

I am wondering if there's another reason for this behavior that I'm not seeing as I'm guessing this line is here for a reason.

### Pull Request

I'd be happy to PR in a patch if you agree this is an issue

**Comment by qstearns** [comment]
Also, for what it's worth, there's a straightforward workaround which is disabling Rails Semantic Logger from adding an appender at all and then adding one manually that matches it's behavior, but I'd prefer to lean on the Rails Semantic Logger defaults

**Comment by qstearns** [comment]
Looks like the behavior was first introduced in:

https://github.com/rocketjob/rails_semantic_logger/commit/a6b3014f8c1cd57a996db48a89588f3547b00775#diff-be997a3bfc8c4579a8129e5eaf3b21e6R75

**Comment by qstearns** [comment]
@reidmorrison just checking in if you've had a chance to take a look at this.

**Comment by qstearns** [comment]
I see how that would work as a workaround, but I'm curious as to the reason behind the current behavior when introducing the appender in `application.rb`. Even if there is a workaround, I can see this causing quite a bit of confusion (like it did for me). Is there a reason you'd want to hang on to the current behavior?

**Comment by reidmorrison** [comment]
Rails Semantic Logger is a hack to try and make Rails work with Semantic Logger. As a result it tries to monkey patch Rails with every new version. If Rails used Semantic Logger directly this gem would not be required and you would not have the issue above.
