### ISSUE TITLE
Cardinality explosion due to payload params

### ISSUE THREAD

**Issue by xrl** [rocketjob/rails_semantic_logger#74]
### Environment

Provide at least:
* Ruby Version. `2.5.1`
* Rails Version. `4.2.8`
* Semantic Logger Version. `4.2.0`
* Rails Semantic Logger Version. `4.2.0`
* Other Application/framework names and versions (e.g. Puma, etc.). `puma`
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.

```
#config/environments/production.rb
  # Disable writing to local filesystem
  config.rails_semantic_logger.add_file_appender = false
```

```
#config/initializers/semantic_logger.rb
require 'semantic_logger'
require 'typhoeus/adapters/faraday'

Ethon.logger.level = :info

def setup_semantic_logger
  SemanticLogger.reopen
  # We're in smart spawning mode.
  # ... code to reestablish socket connections here ...
  SemanticLogger.add_appender(appender: :elasticsearch,
                              application: 'rails',
                              index: "rx-saml-#{Rails.env}",
                              datepattern: '%Y.%m',
                              url: ENV["ELASTICSEARCH_LOGGING_URL"] || "http://localhost:9200",
                              batch_size: 200,
                              flush_interval: 10,
                              timeout_interval: 5,
                              filter: /SAML/)
  SemanticLogger.add_appender(appender: :elasticsearch,
                              application: 'rails',
                              index: "rx-#{Rails.env}",
                              datepattern: '%Y.%W',
                              url: ENV["ELASTICSEARCH_LOGGING_URL"] || "http://localhost:9200",
                              batch_size: 200,
                              flush_interval: 10,
                              timeout_interval: 5,
                              filter: lambda do |log|
                                if log.payload && log.payload[:status] && [200,302].include?(log.payload[:status]) && ["/health", "/ready"].include?(log.payload[:path])
                                  return false
                                elsif log.exception && log.exception.message =~ /^No route matches \[GET\]/
                                  return false
                                elsif log.name =~ class_filter
                                  return false
                                end
                                return true
                              end)
end

# Our staging/prod envs run on Passenger. In the future
# we will use Puma so we should switch to puma.rb configfile
# found in the contractresearchmap repo
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |_forked|
    setup_semantic_logger
    SAML_LOGGER = SemanticLogger['SAML']
  end
else
  setup_semantic_logger
  SAML_LOGGER = SemanticLogger['SAML']
end
```

* Full Stack Trace, if an exception is being raised.

Note:
* Issues reported here should be related to monkey patches applied to Rails to make it use Semantic Logger. 
* For other logging and appender related issues, please report the issue at [Semantic Logger](https://github.com/rocketjob/semantic_logger/issues.

### Expected Behavior

* Describe your expectation of how Semantic Logger should behave, perhaps by showing how the builtin Rails logger behaves.

The default formatter provided to the rails app will log the entire params in the payload. Is there a way to white list properties that should be forwarded so we can keep the cardinality down? Right now our Elasticsearch cluster is rejecting records because we now have 1000+ properties because the params field is very dynamic.

**Comment by reidmorrison** [comment]
The easiest way to limit the payload would be to write your own formatter and supply that to the elastic search appender above: https://rocketjob.github.io/semantic_logger/customize.html.
The formatter can be used to limit/filter out properties you don't want to forward to elastic search.

A more complex, but more specific approach would be to add a filter directly to the logger instance that is generating the large log entries. The name of the logger instance that should be modified is in the log output.

On a side note, it is better to not use `return false` inside a lambda since it will execute the `return` within the code that is executing the lambda, and not just return from the lambda itself. I.e. The filter lambda above will work fine if the `return` keywords are removed.

I looks like filters can become quite complex, so replacing the lambda with a dedicated Module would clean it up significantly. I made a fix in Semantic Logger v4.3.1 to allow a module to be supplied as a filter. For an example see: https://github.com/rocketjob/semantic_logger/blob/e72b36791dfb0d579353dd9ead35048cc3427d93/test/logger_test.rb#L13

**Comment by xrl** [comment]
Thanks for the tip! I finally got around to tackling this issue:

```
PAYLOAD_PARAMS_WHITELIST = %w(id slug SAMLResponse)
PayloadFormatter = Proc.new do |log,appender|
  if log.payload && log.payload[:params].present?
    log.payload[:params] = log.payload[:params].slice(*PAYLOAD_PARAMS_WHITELIST)
  end

  SemanticLogger::Formatters::Raw.new(time_format: :iso_8601, time_key: :timestamp).call(log,appender)
end

  SemanticLogger.add_appender(appender: :elasticsearch,
                              application: 'rails',
                              index: "rx-#{Rails.env}",
                              datepattern: '%Y.%W',
                              url: ENV["ELASTICSEARCH_LOGGING_URL"] || "http://localhost:9200",
                              batch_size: 200,
                              flush_interval: 10,
                              timeout_interval: 5,
                              formatter: PayloadFormatter,
                              filter: lambda do |log|
                                if log.payload && log.payload[:status] && [200,302].include?(log.payload[:status]) && ["/health", "/ready"].include?(log.payload[:path])
                                  return false
                                elsif log.exception && log.exception.message =~ /^No route matches \[GET\]/
                                  return false
                                elsif log.name =~ class_filter
                                  return false
                                end
                                return true
                              end)
```

I had to dig up those options for the Raw formatter so I could reuse it.

**Comment by reidmorrison** [comment]
👍
