### ISSUE TITLE
Repository missing release tags

### ISSUE THREAD

**Issue by alexcruice** [rocketjob/rails_semantic_logger#82]
There haven't been any releases tagged since v4.1.3.

### Expected Behavior
- each release tagged with version
- please tag each release, it makes it much easier to use [GitHub's compare view](https://github.com/rocketjob/rails_semantic_logger/compare) between tags when inspecting changes for dependency upgrade maintenance

### Actual Behavior
- no release tags since v4.1.3, mid 2017
<img width="320" alt="screen shot 2018-12-19 at 10 30 48 am" src="https://user-images.githubusercontent.com/3786095/50191465-bab71e80-0379-11e9-9a65-e933840ee3e6.png">

**Comment by reidmorrison** [comment]
You can thank github desktop for that. It does not push tags to the remote.

**Comment by reidmorrison** [comment]
Setup command line to work with 2FA and pushed the tags using command line git.
