### ISSUE TITLE
Integrate with ActiveJob via ActiveSupport::Notifications

### ISSUE THREAD

**Issue by prikha** [rocketjob/rails_semantic_logger#88]
We could empower the ActiveJob integration with what makes SemanticLogger so special - the payload!

Right now when I add `rails_semantic_logger` to an application with `active_job` I have rather useless lines in the log, most probably duplicated by the adapter internal logging. This could/should be improved however. 

ActiveJob emits a bunch of useful events via `ActiveSupport::Notifications`: 

 - perform_start
 - perform
 - enqueue_at
 - enqueue

Events have structured payload which comes handy in the situations you turn to logs(namely when something isn't working well or takes too much time). Unfortunately ActiveJob already have a subscriber for that and it assumes classical logger in place.

https://github.com/rails/rails/blob/master/activejob/lib/active_job/logging.rb

But we can patch it and have the payload nicely integrated. And then do proper filtering by job class, queue or duration. One probably would want to refuse native job adapter logging when this one is setup.

Overriding `ActiveJob::Logging::LogSubscriber` and re-subscribing to the `*.active_job` events does the trick.

### Pull Request

https://github.com/rocketjob/rails_semantic_logger/pull/87

**Comment by prikha** [comment]
@reidmorrison what do you think?

**Comment by reidmorrison** [comment]
Fixed in #87 

Well Done. Thank you!
