### ISSUE TITLE
Sidekiq 6.0 does not initialize due to a NameError 

### ISSUE THREAD

**Issue by MisterFine1** [rocketjob/rails_semantic_logger#94]
### Environment

Using Ruby 2.6, Rails 5.2, I upgraded Sidekiq to the new 6.0 version this morning, which changes how Sidekiq logging is configured.  Upon startup, I received the following error:

/Users/rfine/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rails_semantic_logger-4.4.2/lib/rails_semantic_logger/engine.rb:111:in `block in <class:Engine>': uninitialized constant Sidekiq::Logging (NameError)

The line of code in rails_semantic_logger that is causing this is:

```
      # Replace the Sidekiq logger
      Sidekiq::Logging.logger = SemanticLogger[Sidekiq] if defined?(Sidekiq)
```

The Sidekiq upgrade notes identify the change -- how Sidekiq logging is newly configured in 6.0:

```
Sidekiq.configure_server do |config|
  config.log_formatter = AcmeCorp::PlainLogFormatter.new
  # config.log_formatter = Sidekiq::Logger::Format::JSON.new
end

```

**Comment by bobvanderlinden** [comment]
@MisterFine1 I made a PR that attempts to solve this issue. Could you give it a look?
