### ISSUE TITLE
Swap Active Job log subscriber instead of loosing all subscriptions

### ISSUE THREAD

**Issue by prikha** [rocketjob/rails_semantic_logger#98]
### Environment

Provide at least:
* Ruby 2.6.5
* Rails 6.x
* Semantic Logger Rails 4.4.3
* Semantic Logger 4.4

### Expected Behavior

Subscriptions to `active_job` notifications declared in the `initializers` should not be lost.

Put this into the initializers:

```rb
# config/initializers/active_job_subscription.rb
ActiveSupport::Notifications.subscribe(/.*\.active_job/) do |event|
  puts "SUBSCRIPTION_WORKS"
end
```
Then scheduling a job should output the text.

### Actual Behavior

Then scheduling a job should output the text. But it doesn't because we have explicitly unsubscribed all subscribers: 

https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/active_job/logging.rb#L128-L132

Which is totally my fault, and now I need to fix it.

### Pull Request

With this PR in place, we will safely swap the subscriber:
https://github.com/rocketjob/rails_semantic_logger/pull/97/files

**Comment by reidmorrison** [comment]
PR merged https://github.com/rocketjob/rails_semantic_logger/pull/97
