### ISSUE TITLE
Does rails_semantic_logger support Rails 6?

### ISSUE THREAD

**Issue by truongnmt** [rocketjob/rails_semantic_logger#99]
### Environment

Provide at least:
* Ruby Version: 2.6.5
* Rails Version: 6.0.2.2
* Semantic Logger Version: 4.6.1
* Rails Semantic Logger Version: 4.4.3

On reading the documentation from **rails_semantic_logger README**, I see that the supported Rails version is:
```
Supports
Rails 3.2, 4, 5
```

Meanwhile from **semantic_logger documentation**:
http://rocketjob.github.io/semantic_logger/rails.html

```
Rails Support
Supports Rails 4.2, 5.0 and 5.1.
```

Not really match together.

However, my question is does rails_semantic_logger support Rails 6? I saw test on Rails 6 environment passed although it's 'Allowed Failures' so I'm doubting :thinking:
https://travis-ci.org/github/rocketjob/rails_semantic_logger

![image](https://user-images.githubusercontent.com/11817656/79543171-ececa380-80c7-11ea-935b-3368ebe6f7e8.png)

What problems does rails_semantic_logger might have on Rails 6? Thanks!

**Comment by reidmorrison** [comment]
I need to remove the supports list from the readme and the docs. Then refer everyone to the Travis file. 
The community added Rails 6 to the supported list. We only have JRuby on the allowed to fail list, even though it is successful nowadays.
We are in the process of upgrading our Rails app to rails 6 so will definitively be using Rails Semantic Logger with Rails 6.

**Comment by reidmorrison** [comment]
Fixed documentation in https://github.com/rocketjob/semantic_logger/commit/e82ef88c1955b007c51e25da5e4935ff49688360

**Comment by truongnmt** [comment]
Thanks for confirming!

@reidmorrison also please update in here as well https://github.com/rocketjob/rails_semantic_logger#supports

> Support
Rails 3.2, 4, 5

**Comment by truongnmt** [comment]
@reidmorrison just open a quick PR #100 to fix the above documentation
